### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by Codetoil** [FuBangkun/ToTheStarsRemake#2]
Hi! I'm the owner of the [original project](https://github.com/Codetoil/tothestars). The original project was licensed under the [LGPL-3.0+](https://github.com/Codetoil/tothestars/blob/master/LICENSE.md), which requires modified versions of the source code be licensed under the same license. Please fix this ASAP!

**Comment by FuBangkun** [comment]
I apologize for forgetting to add the license information on GitHub. I will rectify this as soon as possible. However, I did select this license when releasing the mod on CurseForge and Modrinth. Thank you for bringing this to my attention.

**Comment by Codetoil** [comment]
Oh, btw, the LGPL is special in that you need to include both it and the GPL in your repository, because the LGPL is an amendium to the GPL.

**Comment by FuBangkun** [comment]
I have already added it.

**Comment by FuBangkun** [comment]
By the way, I also plan to add stars for all addons and remove the API interface.
